setup the initial version of google-drive logic to upload a file
Cooperation-org/vc-storage pull request #1
Opened 2024-05-01 14:23 UTC by 0marSalah

i used ejs just to testing the function we ned discuss how i the function will get the file
make sure before `yarn start` you are in google-drive ditrectory

2024-05-01 15:49 UTC, gvelez17 commented on google-drive/dist/server.js
> +            filePath: path.join(__dirname, 'credentials.json'),
great, but lets not hardcode this path in the real code, this is good for a test harness, not in the actual code

2024-05-01 15:50 UTC, gvelez17 commented on google-drive/src/server.ts
> +      mimeType: 'application/json'
oh also lets not checkin /dist, can you .gitignore it, we don't want to check in build targets

2024-05-01 15:51 UTC, gvelez17 commented on google-drive/src/uploader.ts
> +      name: path.basename(filePath),
lets please separate how we get the file from the upload to google drive

there should be a separate methods to accept the file or stream and separate ones to push to the google drive api.  as it is now it conflates reading from a local file with pushing to google drive, so it won't be useful for connecting to front end, lets separate those please

2024-05-01 15:52 UTC, gvelez17 requested changes
needs refactor to separate how we get the data from pushing it to google drive
needs to be able to accept data from front end not only file
do not specify file paths in the main code that should be in test harness
do not check in dist
thanks for work so far!

2024-05-01 16:11 UTC, gvelez17 commented
oh also remove DCO it is such a pain to have to refactor because of it, kill that thing

2024-05-02 19:35 UTC, gvelez17 commented on README.md
>  ```bash
uh we want to change storage based on env variable not whole chunk of code in one place, look up some better patterns to encapsulate this please thanks

2024-05-02 19:37 UTC, gvelez17 requested changes
So all the google drive related stuff should be in one library file

The server should be general

we want to encapsulate the minimal differences we need for each storaage type, the top level should not know or care except for env var or some switch

look up design patterns for encapsulation, ask ai about encapsulating storages like talk to it about what we plan

2024-05-06 14:22 UTC, gvelez17 commented on src/credentials.json
> +{
lets move this out of source into a fixture directory?  its for testing right?

2024-05-06 14:22 UTC, gvelez17 commented on src/models/StorageContext.ts
> +class StorageFactory {
great , this is good!

2024-05-06 14:51 UTC, 0marSalah commented on src/credentials.json
> +{
yes it is

2024-05-07 10:36 UTC, merged